spring:
  jpa:
    # 스프링버전 2.5 이상부터 Hibernate 보다 data.sql이 먼저 실행되는 경우 오류가 발생함
    # 아래와 같이 옵션을 지정하여 순서를 변경해준다.
    #    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /console

application:
  session:
    interval: 1