server:
  port: 9091
  error:
    whitelabel:
      enabled: false

spring:
  profiles:
    active: local
  jpa:
    hibernate:
      naming:
        physical-strategy: workus.core.TableNamingStrategy
    show-sql: true
    properties:
      hibernate:
        format_sql: true
